### ISSUE TITLE
Alterar o rótulo do link que retorna ao índice de links dentro dos posts

### ISSUE THREAD

**Issue by rghedin** [gabrnunes/orbita#11]
O rótulo atual é “🪐 Órbita”, pouco descritivo e meio perdido ali.

Proponho algo mais explicativo, como “« Voltar ao índice de links”. (A setinha dupla é padrão no Manual; use o código HTML `&laquo;` para renderizá-la.)

**Comment by gabrnunes** [comment]
Feito!
