### ISSUE TITLE
Simplificação do CSS

### ISSUE THREAD

**Issue by rghedin** [gabrnunes/orbita#12]
Oi gente! Acho que tem muito CSS do Órbita que não precisaria estar ali. A ideia é que ele herde coisas mais básicas do tema do WordPress.

Fiz alguns testes aqui e funcionou bem. Por exemplo, os vários `line-height` do Órbita deixam o espaçamento entrelinhas esquisitão:

<img width="1483" alt="Captura de Tela 2023-01-16 às 19 23 00" src="https://user-images.githubusercontent.com/19216581/212774031-01b60179-cba3-4c9d-bed0-fef117aa245e.png">

Sem eles, fica bem mais agradável e faz um uso melhor do espaço vertical:

<img width="1483" alt="Captura de Tela 2023-01-16 às 19 23 25" src="https://user-images.githubusercontent.com/19216581/212774083-43f475ce-980c-4381-a4ce-6203e22cca04.png">

Uma sugestão meio maluca seria abolir o main.css que o Órbita injeta e adicionar apenas o que for essencial — como a barra principal de links, no topo, e o botão de upvote. A depender do volume de código, dá para incorporá-lo direto no style.css principal do tema do WordPress. Há condições para tentarmos essa abordagem?

**Comment by gabrnunes** [comment]
Boa, vou dar uma ajustada no CSS. Mas eu discordo com o fato de abolir o main.css, o Órbita é um plugin e ele deve funcionar em qualquer tema, indiferente do CSS do tema ou não, mantendo separado isso fica mais fácil.

**Comment by rghedin** [comment]
Ah, faz sentido, embora eu deteste plugins que acrescentam CSS. (Removo todos via `functions.php` e acrescento o CSS necessário no `style.css` principal do tema.)

Um bom meio termo seria oferecer a opção de carregar o `main.css` ou não nas configurações do Órbita. Acha que é viável?

**Comment by gabrnunes** [comment]
Mas a gente não tem tela de configurações :-(

Sindo que isso será um trabalho extra que não vou conseguir fazer.

**Comment by rghedin** [comment]
Ah, poxa. Tudo bem.

Mas uma coisa que precisamos consertar é puxar os assets do Órbita só em páginas do Órbita. O plugin está carregando o `main.css` e um JavaScript no header em todas as páginas.

**Comment by gabrnunes** [comment]
Resolvido: https://github.com/gabrnunes/orbita/pull/30
