### ISSUE TITLE
Redirecionar o usuário à página do post após a publicação do mesmo

### ISSUE THREAD

**Issue by rghedin** [gabrnunes/orbita#15]
Hoje, o usuário é levado a uma página intermediária, que diz “Tudo certo! Agora você pode acessar seu post.” — a última parte é linkada para o post.

Há dois caminhos que precisam ser contemplados:

* Quando não houver filtragem/moderação, ou seja, o post fore publicado direto, levar o usuário à página do post.
* Quando houver filtragem/moderação, ou seja, o post só for ao ar após um administrador aprová-lo, exigir uma mensagem ao usuário informando que o post será exibido somente após aprovação de um admin.

**Comment by gabrnunes** [comment]
Verifiquei aqui e realmente não tem como fazer um redirect automático pois o plugin foi feito usando `shortcode`. O PHP só deixa fazer redirect adicionando o `header` no começo do arquivo, mas como o plugin é um shortcode, ele vai estar lá no meio e não funciona o redirect via PHP.

**Comment by rghedin** [comment]
Lembrei de uma coisa espartana, mas que talvez funcione (?): esta meta tag:

`<meta http-equiv = "refresh" content = "5; url = https://urldedestino.com" />`

Tem como injetar isso naquela página “Acessar seu post”, que aparece após enviar um? Aí podemos incluir a mensagem “Aguarde 5 segundos para ser redirecionado (ou clique aqui)”.

**Comment by gabrnunes** [comment]
Não sei se isso é uma boa prática, hahaha.

E como se trata de um Shortcode, não daria pra mudar o header. Daria pra fazer uma outra gambiarra, eu acho, usando Javascript, mas ainda assim é uma gambiarra.

**Comment by altendorfme** [comment]
Estava fazendo alguns testes:

Depois de:
`$post_id = wp_insert_post($post);`

Adicionei:
```
session_start();
$_SESSION['orbita_new_post_id'] = $post_id;
```

Ai adicionei tambem:

```
add_action('wp_loaded', function () {
	session_start();
	if(isset($_SESSION['orbita_new_post_id'])) {
		$post_id = $_SESSION['orbita_new_post_id'];
		unset($_SESSION['orbita_new_post_id']);
		wp_redirect(home_url('/?p=' . $post_id));
		exit();
	}
});
```

Mas bizarramente, ele só tá pegando o session se eu recarregar a pagina de postar novamente, ai faz o redirect correto pelo header, se alguém tiver ideia do porque a session registrada não chega no proximo hook ta ai a solução 😅

**Comment by altendorfme** [comment]
@gabrnunes @claromes surgiu uma ideia que funciona

Passar toda a parte do `$_POST` de dentro da função do shortcode para uma nova antes do headers, no caso testei e funcionou com `template_redirect`, e deve funcionar na `wp_loaded`:

```
add_action('template_redirect', 'test_redirect');
function test_redirect() {
	if ( $_POST && isset( $_POST['orbita_post_title'] ) ) {

		$already_posted = get_page_by_title( wp_unslash( $_POST['orbita_post_title'] ), OBJECT, 'orbita_post' );

		//if ( get_current_user_id() === $already_posted->ID && $already_posted->post_author ) {
		//	$html = 'Parece que este post <a href="' . home_url( '/?p=' . $already_posted->ID ) . '">já existe</a>.';
		//	return $html;
		//}

		$default_category = get_term_by( 'slug', 'link', 'orbita_category' );

		if ( ! isset( $_POST['orbita_post_content'] ) ) {
			$orbita_post_content = '';
		} else {
			$orbita_post_content = $_POST['orbita_post_content'];
		}

		if ( ! isset( $_POST['orbita_post_url'] ) ) {
			$orbita_post_url = '';
		} else {
			$orbita_post_url = sanitize_text_field( wp_unslash( $_POST['orbita_post_url'] ) );
		}

		$post    = array(
			'post_title'   => wp_unslash( $_POST['orbita_post_title'] ),
			'post_content' => $orbita_post_content,
			'tax_input'    => array(
				'orbita_category' => array( $default_category->term_id ),
			),
			'meta_input'   => array(
				'external_url' => $orbita_post_url,
			),
			'post_status'  => 'publish',
			'post_type'    => 'orbita_post',
		);
		$post_id = wp_insert_post( $post );
		wp_safe_redirect(get_permalink($post_id));
	}
}
```

Em caso de erro (_no codigo comentado_) daria pra devolver pra tela de Postar com parametros, tipo:

```
wp_safe_redirect( add_query_arg( array( 'error' => 'duplicated' ), '/orbita/postar' ) );
```

Oque acham? Algum risco? Melhorias?

**Comment by gabrnunes** [comment]
Parece uma boa ideia! :)

**Comment by rghedin** [comment]
Consegue subir um PR com essa alteração, @altendorfme?

**Comment by rghedin** [comment]
Resolvido.
