### ISSUE TITLE
Disparar notificações apenas para posts que não foram criados pelo usuário

### ISSUE THREAD

**Issue by rghedin** [gabrnunes/orbita#23]
Estou recebendo dobrado nos posts publicados por mim — pelo Órbita e pelo próprio WordPress.

O ideal é que o sistema de notificação de comentários global do Órbita só entre em ação em posts assinados por outros usuários que não o admin.

Algo como: “Notifique todos os comentários de todos os posts, exceto os publicados pelo admin que recebe as notificações.”

**Comment by gabrnunes** [comment]
esse também foi resolvido né?

**Comment by rghedin** [comment]
Sim!
