### ISSUE TITLE
Dúvidas - Front-end

### ISSUE THREAD

**Issue by claromes** [gabrnunes/orbita#3]
Oi @gabrnunes e @rghedin.

Eu montei uma todo list pra me organizar e surgiram algumas dúvidas:

1. o MdU está usando o child theme "ten-years"? Me parece que o estilo foi feito seguindo o theme "MdU2020". Qual o correto?
2. O `vote button` é com ou sem texto? O layout está quebrado e como no código tem o ícone + texto surgiu a dúvida.
3. Seguindo o modelo do HN, o formulário para postar o link não tem header, no Órbita tem. Vai manter? Não sei se faz sentido manter o header com "Postar" nessa página.
4. Seguindo o modelo do HN, quando é uma discussão e não um link, não é mostrado nenhum link. No Órbita mostra o link local. Podemos tirar?
5. A classe `orbita-post-date`, onde tem as infos com autor e data na listagem dos links, poderia ter uma fonte menor. Sugiro 0.70rem. O que acham?

Vou fazer o PR com o readme e com a todo list e tirando essas dúvidas já dá pra ir pro código. ;)

**Comment by gabrnunes** [comment]
Oi @claromes,

1 - Sim, o tema mudou depois que eu criei o plugin. O correto hoje é o `twentynineteen`, padrão do Wordpress.
2 - Sabe que não lembro? Eu acho que o botão de votar é apenas um ícone de "up"
3 - Acho que isso foi uma sugestão que o Ghedin pediu pra colocar
4 - Não entendi muito bem. Ele teria que ter o link pra pessoa clicar e abrir a discussão, não?
5 - Pode ajustar sim

**Comment by claromes** [comment]
Beleza!

Sobre o 4, seria esse texto aqui:
![Captura de tela 2022-10-09 113842](https://user-images.githubusercontent.com/28742647/194762921-c4a855a1-06c3-45b2-a860-53cfe9b60a70.jpg)

Que quando for pra produção deve aparecer o "manualdousuario.net" e no HN fica sem esse texto, indicando uma discussão interna. Vai mantê-lo?

**Comment by rghedin** [comment]
A gente consegue personalizar esse texto para quando for discussão? Se sim, seria legal sinalizar no mesmo formato — algo como “debate” ou “interno”. Se não, pode tirar.
