### ISSUE TITLE
“Degradar” pontuação com passar dos dias

### ISSUE THREAD

**Issue by rghedin** [gabrnunes/orbita#32]
Uma ideia que tive aqui para deixar a capa mais dinâmica: a cada dia que passa, um post “perde” um percentual da pontuação, abrindo espaço para novos posts.

Pode ser algo do tipo:

* Após 24h (1 dia), perde 10% dos pontos que tiver;
* Após 48h (2 dias), perde 25% dos pontos;
* Após 72h (3 dias), perde 50% dos pontos; e
* Após 96h (4 dias), perde 80% dos pontos.

Essa penalização poderia ser implementada como algo “hidden”, ou seja, no front-end o post continuaria exibindo a pontuação total dada pelos usuários.

Acham que faz sentido?

**Comment by gabrnunes** [comment]
Na verdade isso já acontece, o "ALGORITMO" do Chuvisco e agora do Órbita é assim:

Pontos totais = <kbd>2 * Número de comentários</kbd> + <kbd>1 * Número de votos</kbd> + <kbd>1 * Número de votos invisíveis</kbd>

Depois é feito um outro cálculo que pega o número de horas que passaram desde a publicação e faz uma nova conta:

Pontos totais = <kbd>Pontos totais</kbd> - <kbd>Número de horas passadas / 10</kbd>

O que podemos fazer é tentar calibrar melhor, ao invés de `10` dividir por `8`?

**Comment by rghedin** [comment]
Vamos tentar fazer essa calibragem.

**Comment by rghedin** [comment]
Acho que temos um novo problema: posts com muitos comentários demoram muito para saírem da capa, mesmo quando a conversa já morreu.

É possível acelerar a degradação para posts com +X comentários?

Exemplo: hoje, todos os posts perdem 0,2 ponto por hora, certo? Digamos que, ao bater 20 comentários, um post passe a perder 0,6 ponto por hora. Dá para fazer isso?

**Comment by gabrnunes** [comment]
Acho que dá sim, mas uma opção também é diminuir o número de pontos que uma publicação ganha por comentários. Lá na página do ranking muda  o shortcode para `[orbita-ranking comment-points="1"]`

**Comment by rghedin** [comment]
Uhhh, bem lembrado. Mudei, deu uma boa diferença. Vamos acompanhar.
