### ISSUE TITLE
Listagem por ordem cronológica inversa no back-end

### ISSUE THREAD

**Issue by rghedin** [gabrnunes/orbita#36]
Aparentemente, a listagem de posts no back-end (`https://manualdousuario.net/wp-admin/edit.php?post_type=orbita_post`) é, por padrão, em ordem alfabética.

Não faz muito sentido. O ideal é que seja em ordem cronológica inversa, com os posts mais recentes no topo.

Acho que [este código](https://wordpress.stackexchange.com/a/125889) ajeita as coisas, mas não sei como implementar diretamente no plugin.

**Comment by gabrnunes** [comment]
Mas nesse caso não é só clicar na coluna de data pra ordenar?

**Comment by rghedin** [comment]
Isto no `functions.php` resolve o problema:

```
function wpse_81939_post_types_admin_order( $wp_query ) {
  if (is_admin()) {
    $post_type = $wp_query->query['post_type'];
    if ( $post_type == 'orbita_post') {
      $wp_query->set('orderby', 'date');
      $wp_query->set('order', 'DESC');
    }
  }
}
add_filter('pre_get_posts', 'wpse_81939_post_types_admin_order');
```
