### ISSUE TITLE
“Converter” links de vídeo em embeds no corpo do texto

### ISSUE THREAD

**Issue by rghedin** [gabrnunes/orbita#38]
Fui postar [um vídeo](https://manualdousuario.net/orbita-post/video-travellers-rest-simulador-de-estalagem/) no Órbita e tive essa ideia: exibir o embed (vídeo incorporado) direto no Órbita.

Isso seria possível?

**Comment by claromes** [comment]
Assim?

![Captura de tela 2023-02-18 193725](https://user-images.githubusercontent.com/28742647/219902625-dc55d2e7-d747-4c12-882f-30270ae99254.jpg)

Acho que dá... Mas quais sites vamos verificar?
- YouTube
- Vimeo
- TikTok (pq não?)
- Dailymotion (ainda usam?)

Algum outro?

**Comment by rghedin** [comment]
Sim, @claromes, mas eu marquei bobeira: o WordPress já faz esse trabalho no conteúdo do post. É só copiar a URL do YouTube ali que o player aparece ([veja](https://manualdousuario.net/orbita-post/video-travellers-rest-simulador-de-estalagem/)) 😬
