### ISSUE TITLE
Contadores de comentários da capa desatualizados (cache?)

### ISSUE THREAD

**Issue by rghedin** [gabrnunes/orbita#45]
Um leitor apontou que os contadores de comentários dos posts [na capa do Órbita](https://manualdousuario.net/orbita/) estão errados. De cara imaginei que fosse um problema de cache e, de fato, ao acessar a mesma página logado e deslogado, a em que estava logado mostrava corretamente os números dos comentários.

Usamos a CDN/cache da Cloudflare. Alguma ideia de como evitar que aqueles números fiquem empacados?

**Comment by gabrnunes** [comment]
vix, não faço ideia :-( 

não existe uma forma de limpar o cache do CloudFlare com mais frequencia? Não sei se isso vai dar algum problema.

Pra mim aqui o Cache é tão "forte" que às vezes nem dando um CTRL + SHIFT + R ele atualiza hahaha

**Comment by rghedin** [comment]
Pois é, o cache é forte mesmo. Tem um jeito de deixar páginas fora do cache. Vou tentar isso. Como a visitação à capa do Órbita ainda é baixa, talvez não impacte tanto o desempenho do servidor.

**Comment by gabrnunes** [comment]
Deu certo?

**Comment by rghedin** [comment]
Aparentemente, sim! Se puderem testar aí também: abra duas janelas do Órbita, uma logado(a), outra deslogado e no modo anônimo. Se ambas estiverem iguais, é porque deu certo. (Aqui está dando.)
