### ISSUE TITLE
Parâmetros UTM nos links externos

### ISSUE THREAD

**Issue by rghedin** [gabrnunes/orbita#50]
É possível acrescentarmos automaticamente parâmetros UTM aos links publicados no Órbita? Estive pensando aqui e é uma ótima maneira de “divulgarmos” o Órbita entre donos de sites.

Eu já uso um padrão para a newsletter, que podemos adaptar para o Órbita. Ficaria assim:

`?utm_source=ManualdoUsuarioNet&utm_medium=Orbita`

**Comment by gabrnunes** [comment]
Tem sim, é só procurar em todos os lugares que a url do link é colocado e adicionar isso manualmente.

Por exemplo aqui na linha 222 https://github.com/gabrnunes/orbita/blob/main/orbita.php#L222

**Comment by rghedin** [comment]
Boa! Alteração feita no https://github.com/gabrnunes/orbita/pull/51
