### ISSUE TITLE
Sinalizar melhor posts de conversas

### ISSUE THREAD

**Issue by rghedin** [gabrnunes/orbita#53]
[Ideia do borges](https://manualdousuario.net/orbita-post/leiaute-do-orbita/#comment-202462).

Fiz outros mockups e um que me agradou consiste em remover o contador da lista e acrescentar um balão somente nos posts de conversas (aí dá para tirar o “conversa” no final do título).

<img width="886" alt="Captura de Tela 2023-03-02 às 13 31 27" src="https://user-images.githubusercontent.com/19216581/222492008-8b5d83d5-5243-4870-9c18-ce67d43efdb8.png">

Não lembro se chegamos a debater a listagem com contador, o porquê daquilo estar ali. Lembra, @gabrnunes?

**Comment by gabrnunes** [comment]
Oie! Acho legal colocar o ícone sim, ficou maneiro.

Sobre o contador eu coloquei por se tratar de um ranking e pq o Hacker News tem, mas não sou apegado, podemos tirar sim.

**Comment by rghedin** [comment]
Aproveitar a mesma issue para outra alteração relacionada: acrescentar um emoji de cadeado (🔒) em posts que tiverem os comentários fechados (`!comments_open()`).

**Comment by altendorfme** [comment]
@rghedin o balão foi adicionado do lado direito, migra ele e o cadeado para o lado esquerdo?

**Comment by rghedin** [comment]
Isso, @altendorfme, todos os ícones do lado esquerdo.

Um detalhe: o cadeado não está no código. Eu insiro ele manualmente quando tranco um post para comentários. Seria legal se fosse automático, ou seja, se o post estiver fechado para comentários, aparece o cadeado.

Nessa ordem: `cadeado` (se houver) `balão` (se for um post da categoria Conversas) `título`

```
🔒 💬 Exemplo de título para um post duplicado (trancado para comentários) da categoria “Conversas”
```

**Comment by rghedin** [comment]
Resolveu!

**Comment by rghedin** [comment]
Resolvido!

**Comment by altendorfme** [comment]
Jajá subo uma PR com esse ajuste no scss também ;)
