### ISSUE TITLE
Permitir editar/deletar comentários

### ISSUE THREAD

**Issue by mvcmendes** [gabrnunes/orbita#55]
Hoje fiz um comentário e, alguns segundos depois, senti a necessidade de editá-lo. Como não existe essa possibilidade, pensei em deletá-lo para, em seguida, postar novamente. Mas também não há esta possibilidade. Seria interessante permitir um ou outro, já que suponho que eu não seja o único que sofra de arrependimento pós-publicação. 😛

**Comment by gabrnunes** [comment]
Acho que esse daria pra resolver com um plugin, o que acha @rghedin? 
https://www.wpbeginner.com/plugins/allow-users-edit-comments-wordpress/

**Comment by altendorfme** [comment]
Tenta o https://br.wordpress.org/plugins/advanced-access-manager/, é um plugin bem avançado para gerencias permissões por usuários e/ou grupos, eu já usei por exemplo para um grupo de usuários que só poderiam postar em um post type especifico, e inclusive uso para sumir do menu/acesso aqueles plugins mais saidinhos

**Comment by rghedin** [comment]
Hmm, esse eu não conhecia, @altendorfme. Edito bastante coisa da experiência dos leitores no painel (todos com roles `subscriber`), a maioria editando o `functions.php` e com o plugin [Roles & Capabilities](https://br.wordpress.org/plugins/leira-roles/). (Na real, acho que ele faz a mesma coisa, no fim das contas.)

O problema do Órbita, nesse aspecto, é que ele não gera “capabilities” — aquelas privilégios editáveis, do tipo `edit_comment`, `create_posts` etc. Aí não tem como personalizar um “role” para o post type do Órbita. Eu achava que tinha uma issue disso aqui, mas devo ter comentado no grupo do Telegram. Vou criar a issue qualquer hora dessas.

**Comment by altendorfme** [comment]
Vejo aqui:
https://github.com/gabrnunes/orbita/blob/6cd964a351ab4806abfe60e4594804bbbfd9f9e6/orbita.php#L87
o registro do novo post type do orbita saiu `capability_type` de post, que é padrão.

trocar essa linha por:

```
'map_meta_cap'    => true,
'capability_type' => 'orbita',
'capabilities' => [
        'edit_post'                 => 'edit_orbita',
        'read_post'                 => 'read_orbita',
        'delete_post'               => 'delete_orbita',
        'create_posts'              => 'create_orbitas',
        'delete_posts'              => 'delete_orbitas',
        'delete_others_posts'       => 'delete_others_orbitas',
        'delete_private_posts'      => 'delete_private_orbitas',
        'delete_published_posts'    => 'delete_published_orbitas',
        'edit_posts'                => 'edit_orbitas',
        'edit_others_posts'         => 'edit_others_orbitas',
        'edit_private_posts'        => 'edit_private_orbitas',
        'edit_published_posts'      => 'edit_published_orbitas',
        'publish_posts'             => 'publish_orbitas',
        'read_private_posts'        => 'read_private_orbitas'
]
```

Dessa forma irá criar novas capabilities especificas, sem misturar as do post site com do orbita, vale uma olhada em (https://developer.wordpress.org/reference/functions/register_post_type/#capability_type)

Isso deveria ser suficiente para liberar nesses plugins a opção de ligar e desligar as regras entre grupo de usuários, essa determinação pode (e recomendaria) ser feita direto no plugin ou `functions.php`, assim não corre riscos ao desabilitar plugins:

```
add_action( 'init', function () {
	  $role = get_role( 'subscriber' );

	  $role->add_cap( 'edit_orbita' ); 
	  $role->add_cap( 'edit_orbita' ); 
	  $role->add_cap( 'edit_others_orbita' ); 
	  $role->add_cap( 'publish_orbita' ); 
	  $role->add_cap( 'read_orbita' ); 
	  $role->add_cap( 'read_private_orbita' ); 
	  $role->add_cap( 'delete_orbita' ); 
	  $role->add_cap( 'edit_published_orbita' );
	  $role->add_cap( 'delete_published_orbita' );
});
```

**Comment by rghedin** [comment]
Ah, que beleza! Obrigado, @altendorfme! Vou ver se consigo um tempo para mexer nisso amanhã e, aí, já alterar o plugin/código aqui no repositório mesmo. (Aliás, se quiser ter a honra, pode submeter um PR.)

**Comment by rghedin** [comment]
Edição temporária (2min) [implementada](https://manualdousuario.net/markdown-edicao-comentarios-tema-wordpress/).
