### ISSUE TITLE
Paginação na capa/populares

### ISSUE THREAD

**Issue by rghedin** [gabrnunes/orbita#56]
Um leitor comentou que é difícil encontrar posts antigos no Órbita, e só aí me toque que a capa não tem paginação — ela mostra só os 20 posts mais populares do momento e acabou.

É possível colocar paginação, para que a pessoa navegue por todo o conteúdo do Órbita, ordenado pela popularidade do momento?

**Comment by gabrnunes** [comment]
Do jeito que foi feito hoje não dá não.

O ranking é calculado depois de fazer a query de posts, dai se colocar paginação ele vai se perder todo. Teria que refatorar tudo. O ideal para encontrar posts antigos é ir na navegação por data dai.

**Comment by math42gimenez** [comment]
Boa tarde a todos.

Gostaria de tentar fazer essa, se possivel. Mas estou tentando entender a logica.
Pensei no seguinte: fazer esse calculo (abaixo) na query SQL usando um add_filter da vida:

		$total_points    = ( (int) $points_comments * (int) $comment_points ) + ( (int) $points_votes * (int) $vote_points ) + ( (int) $invisible_votes * (int) $vote_points );

		if ( $total_points > 0 ) {
			$total_points = $total_points - ( $time_elapsed / 3 );
		}
Ai quanto a isso tenho uma duvida: 
Existem dois queries sendo mesclados que fazem uso desse calculo. O de posts é mesmo necessário?

**Comment by gabrnunes** [comment]
Ele existe por uma solicitação do @rghedin para que os posts do Manual pudessem aparecer no Órbita, seria mais uma decisão de produto/negócio.

Por mim podemos tirar, o que acha @rghedin ?

**Comment by rghedin** [comment]
É, acho que dá para tirar. (Aí provavelmente resolvemos aquele bug (https://github.com/gabrnunes/orbita/issues/33) dos posts fixados (`sticky`) que aparecem no Órbita automaticamente, né?
