### ISSUE TITLE
Pesquisa com resultados limitados ao Órbita

### ISSUE THREAD

**Issue by rghedin** [gabrnunes/orbita#61]
Consegui criar um formulário de pesquisa que restringe os resultados ao custom post type do Órbita. Está funcionando [no **Manual**](https://manualdousuario.net/orbita/) (coloquei o formulário no final da lista de posts).

Acrescentei o formulário editando a página, mas talvez o ideal seja embutir ele no `orbita.php`. Aí eu me enrolo e não sei como fazer.

Segue o código:

```html
<form role="search" method="get" id="searchform" action="<?php echo get_site_url(); ?>">
<div>
<label style="display: block; margin-top: 6rem;" for="s">Pesquise no Órbita:</label>
<input type="text" class="search-field" value="" name="s" id="s" />
<input type="hidden" value="1" name="sentence" />
<input type="hidden" value="orbita_post" name="post_type" />
<input type="submit" class="search-submit" value="Pesquisar" />
</div>
</form>
```

**Comment by gabrnunes** [comment]
como o órbita funciona por shortcodes, a única for seria criar um novo shortcode com esse formulário, mas não sei se vale a pena.

Acho que pode deixar dessa forma que vc fez mesmo.

PS: desculpa a demora em responder

**Comment by rghedin** [comment]
Seguimos assim, então!
