### ISSUE TITLE
Erros em propriedade "post_author" e variável $orbita_post

### ISSUE THREAD

**Issue by rghedin** [gabrnunes/orbita#64]
O console de registros do PHP do WordPress.com está jogando dois erros repetidamente do Órbita, provavelmente relacionados (referem-se à mesma linha do arquivo `orbita.php`).

O primeiro:

```
message
PHP Warning:  Attempt to read property "post_author" on null in /srv/htdocs/wp-content/plugins/orbita-1.1.6/orbita.php on line 225

severity
Warning

kind
plugins

name
orbita-1.1.6

file
/srv/htdocs/wp-content/plugins/orbita-1.1.6/orbita.php

line
225

timestamp
2023-07-18T19:14:34.000Z

atomic_site_id
150130470
```

E o segundo:

```
message
PHP Warning:  Undefined variable $orbita_post in /srv/htdocs/wp-content/plugins/orbita-1.1.6/orbita.php on line 225

severity
Warning

kind
plugins

name
orbita-1.1.6

file
/srv/htdocs/wp-content/plugins/orbita-1.1.6/orbita.php

line
225

timestamp
2023-07-18T19:14:34.000Z

atomic_site_id
150130470
```

**Comment by claromes** [comment]
Talvez alguém apagou a conta (um usuário pode fazer isso ou só você faz?), afinal não dá pra postar sem ter login.
Mas pra resolver o erro é só verificar se o autor é nulo ou não. Eu acho que não temos essa verificação.

**Comment by rghedin** [comment]
Hmmm, faz sentido — dois ou três leitores pediram para excluir seus perfis no Órbita. O melhor caminho é implementar a verificação, certo? Acha viável, @claromes?

**Comment by claromes** [comment]
Sim. É tranquilo. Faço essa semana.

**Comment by gabrnunes** [comment]
Saiu a release: https://github.com/gabrnunes/orbita/releases/tag/1.1.7 @rghedin

**Comment by rghedin** [comment]
Atualizado. Obrigado, @claromes @gabrnunes!

Só um detalhe: notei que, na área de plugins do WordPress, a versão do Órbita não mudou na nova versão — continua aparecendo 1.1.6.

<img width="838" alt="Captura de Tela 2023-07-25 às 08 08 56" src="https://github.com/gabrnunes/orbita/assets/19216581/c439992a-bb69-4e07-863e-145413525169">

**Comment by claromes** [comment]
A atualização no arquivo é feita pela action "Update version" (é preciso inserir a versão no campo e rodá-la). Isso vai gerar um novo ZIP (disponível na aba `code`) com a versão atualizada. Acho que só o @gabrnunes consegue rodar essa action.

**Comment by claromes** [comment]
> Só um detalhe: notei que, na área de plugins do WordPress, a versão do Órbita não mudou na nova versão — continua aparecendo 1.1.6.
> 
> <img alt="Captura de Tela 2023-07-25 às 08 08 56" width="838" src="https://user-images.githubusercontent.com/19216581/255880958-c439992a-bb69-4e07-863e-145413525169.png">

@rghedin  O erro foi resolvido?

**Comment by claromes** [comment]
`Ruby Sass has reached end-of-life and should no longer be used.` Isso talvez pode causar o erro, mas me parece apenas uma informação.
A diferença entre essa task com erro e a task de check do PR é o push... Talvez o erro seja de conflitos, pois ele não faz pull antes... Estou chutando (`Error: Process completed with exit code 1.` não detalha muito).

Minha ideia com as actions era facilitar, mas não ajudou... Caso isso não resolva podemos tirar essas tasks, e usar o zip dos assets das tags (que vai todo o código do repositório e me parece que o Ghedin usa esse arquivo) e criar um template para PR lembrando de alterar a versão do plugin.

O que acha?

**Comment by rghedin** [comment]
> > Só um detalhe: notei que, na área de plugins do WordPress, a versão do Órbita não mudou na nova versão — continua aparecendo 1.1.6.
> > <img alt="Captura de Tela 2023-07-25 às 08 08 56" width="838" src="https://user-images.githubusercontent.com/19216581/255880958-c439992a-bb69-4e07-863e-145413525169.png">
> 
> @rghedin O erro foi resolvido?

Sim!

**Comment by gabrnunes** [comment]
Acho que faz sentido sua sugestão @claromes :)

**Comment by rghedin** [comment]
Testei [a nova versão](https://github.com/gabrnunes/orbita/releases/tag/1.1.8) e temos dois problemas, um grave e um ameno:

* Grave: continua o erro em que todos os links internos do Órbita dão erro 404 ([relatado aqui](https://github.com/gabrnunes/orbita/pull/65#issuecomment-1652151210)).
* Ameno: a versão no GitHub é 1.1.8, mas ao instalar o plugin é exibida como 1.1.7.

**Comment by gabrnunes** [comment]
Pode testar, @rghedin? https://github.com/gabrnunes/orbita/releases/tag/1.1.9

**Comment by rghedin** [comment]
Testando no staging primeiro. Aviso aqui dos resultados.

**Comment by rghedin** [comment]
Corrigido no PR #70

**Comment by rghedin** [comment]
Não sei se tem relação, mas peguei dois erros no registro, na versão 1.1.11, agora que se parece com o dali de cima, mas é um pouco diferente:

```
message
PHP Warning:  Attempt to read property "term_id" on bool in /srv/htdocs/wp-content/plugins/orbita-1.1.11/orbita.php on line 463

severity
Warning

kind
plugins

name
orbita-1.1.11

file
/srv/htdocs/wp-content/plugins/orbita-1.1.11/orbita.php

line
463

timestamp
2023-08-09T17:25:17.000Z

atomic_site_id
150130470
```

E

```
message
PHP Warning:  Attempt to read property "ID" on null in /srv/htdocs/wp-content/plugins/orbita-1.1.11/orbita.php on line 440

severity
Warning

kind
plugins

name
orbita-1.1.11

file
/srv/htdocs/wp-content/plugins/orbita-1.1.11/orbita.php

line
440

timestamp
2023-08-09T17:25:17.000Z

atomic_site_id
150130470
```
