### ISSUE TITLE
Quando podemos testar?

### ISSUE THREAD

**Issue by rghedin** [gabrnunes/orbita#7]
O Manual tem [um staging](https://staging.manualdousuario.net) que já está com o tema novo (ainda não finalizado, baseado no underscores). 

Quando podemos testar o plugin ali?

**Comment by gabrnunes** [comment]
@rghedin acho que já pode baixar o plugin e instalar lá, se me der um login te ajudo a configurar pra gente testar, o que acha?

**Comment by gabrnunes** [comment]
@rghedin coloquei no ar: https://staging.manualdousuario.net/orbita/

**Comment by rghedin** [comment]
@gabrnunes estava dando uma olhada aqui no front-end. Talvez a gente possa reduzir o CSS do plugin? Tem algumas coisas ali que me parecem redundantes, como cor dos links — imagino que o plugin possa herdar isso do tema do WordPress sem qualquer prejuízo.

Vou tentar dar uma fuçada aqui e submeter pull requests.

**Comment by claromes** [comment]
@rghedin Pode me mandar o tema novo?

**Comment by rghedin** [comment]
[Aqui](https://arquivos.ghed.in/dez-20221115.zip), @claromes. Ainda não está finalizado, mas acho que o grosso do leiaute é isso aí/não terá muitas alterações.

**Comment by gabrnunes** [comment]
Ajustei os bugs de layout e outras coisinhas, podemos colocar em staging na segunda! :)
