### ISSUE TITLE
Novo ícone de votar quebrou o dark mode

### ISSUE THREAD

**Issue by gil** [gabrnunes/orbita#87]
Olá! Não sei se é algum problema aqui do meu lado, mas parece que o novo ícone de votar que foi introduzido em https://github.com/gabrnunes/orbita/commit/82218e75ddc8320d714e3f048b12670f76a3fb7b quebrou no dark mode:

<img width="434" alt="image" src="https://github.com/gabrnunes/orbita/assets/116157/483fa773-54e9-43f6-9214-de6e7585e097">

**Comment by rghedin** [comment]
Já corrigido no PR #86.
